// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnsoGC4ZK9CQfNMkVuQf_4G-D82WbOFgc',
    appId: '1:187564198256:web:a95607b5b146e647dfe7b5',
    messagingSenderId: '187564198256',
    projectId: 'foodrecipe-5ae5a',
    authDomain: 'foodrecipe-5ae5a.firebaseapp.com',
    storageBucket: 'foodrecipe-5ae5a.firebasestorage.app',
    measurementId: 'G-L95NXZL036',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_3bDsgeAGEv2tiHwDi6CzT5LNcXydsdQ',
    appId: '1:187564198256:android:235af068dcfd7bbadfe7b5',
    messagingSenderId: '187564198256',
    projectId: 'foodrecipe-5ae5a',
    storageBucket: 'foodrecipe-5ae5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmp8CW22imN5JhKnHATrGxZLXgqaA2xyg',
    appId: '1:187564198256:ios:c5b1d6b320affb9bdfe7b5',
    messagingSenderId: '187564198256',
    projectId: 'foodrecipe-5ae5a',
    storageBucket: 'foodrecipe-5ae5a.firebasestorage.app',
    iosBundleId: 'com.example.dapurku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmp8CW22imN5JhKnHATrGxZLXgqaA2xyg',
    appId: '1:187564198256:ios:c5b1d6b320affb9bdfe7b5',
    messagingSenderId: '187564198256',
    projectId: 'foodrecipe-5ae5a',
    storageBucket: 'foodrecipe-5ae5a.firebasestorage.app',
    iosBundleId: 'com.example.dapurku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnsoGC4ZK9CQfNMkVuQf_4G-D82WbOFgc',
    appId: '1:187564198256:web:91d2e5e21c18704fdfe7b5',
    messagingSenderId: '187564198256',
    projectId: 'foodrecipe-5ae5a',
    authDomain: 'foodrecipe-5ae5a.firebaseapp.com',
    storageBucket: 'foodrecipe-5ae5a.firebasestorage.app',
    measurementId: 'G-65R16LGLN2',
  );
}
